// Curated list of common Google Fonts used in templates.
// Static (no runtime API call). Keep alphabetical.
export const GOOGLE_FONTS: ReadonlyArray<string> = [
  "Abril Fatface",
  "Anton",
  "Archivo",
  "Archivo Black",
  "Barlow",
  "Bebas Neue",
  "Bitter",
  "Cabin",
  "Cormorant Garamond",
  "DM Sans",
  "DM Serif Display",
  "Dancing Script",
  "Fira Sans",
  "Hind",
  "IBM Plex Mono",
  "IBM Plex Sans",
  "IBM Plex Serif",
  "Inconsolata",
  "Inter",
  "Josefin Sans",
  "Karla",
  "Lato",
  "League Spartan",
  "Libre Baskerville",
  "Libre Franklin",
  "Lora",
  "Manrope",
  "Merriweather",
  "Montserrat",
  "Mulish",
  "Noto Sans",
  "Noto Serif",
  "Nunito",
  "Nunito Sans",
  "Open Sans",
  "Oswald",
  "Outfit",
  "PT Sans",
  "PT Serif",
  "Pacifico",
  "Playfair Display",
  "Plus Jakarta Sans",
  "Poppins",
  "Quicksand",
  "Raleway",
  "Roboto",
  "Roboto Condensed",
  "Roboto Mono",
  "Roboto Serif",
  "Roboto Slab",
  "Rubik",
  "Source Sans 3",
  "Source Serif 4",
  "Space Grotesk",
  "Space Mono",
  "Syne",
  "Ubuntu",
  "Urbanist",
  "Work Sans",
  "Yanone Kaffeesatz",
  "Zilla Slab",
];

export function isGoogleFont(name: string): boolean {
  return GOOGLE_FONTS.includes(name);
}
