// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/get-credits.ts
import { createClient } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_credits_default = defineTool({
  name: "get_credits",
  title: "Consultar cr\xE9ditos",
  description: "Retorna o saldo de cr\xE9ditos individuais do usu\xE1rio autenticado no Creator.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "N\xE3o autenticado." }],
        isError: true
      };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("credits, max_credits, credits_expire_at").eq("id", ctx.getUserId()).maybeSingle();
    if (error) {
      return {
        content: [{ type: "text", text: error.message }],
        isError: true
      };
    }
    if (!data) {
      return {
        content: [{ type: "text", text: "Perfil n\xE3o encontrado." }],
        isError: true
      };
    }
    return {
      content: [
        {
          type: "text",
          text: `Cr\xE9ditos dispon\xEDveis: ${data.credits ?? 0}` + (data.max_credits ? ` (limite: ${data.max_credits})` : "") + (data.credits_expire_at ? ` \u2014 expira em ${data.credits_expire_at}` : "")
        }
      ],
      structuredContent: {
        credits: data.credits ?? 0,
        max_credits: data.max_credits ?? null,
        credits_expire_at: data.credits_expire_at ?? null
      }
    };
  }
});

// src/lib/mcp/tools/list-brands.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_brands_default = defineTool2({
  name: "list_brands",
  title: "Listar marcas",
  description: "Lista as marcas \xE0s quais o usu\xE1rio autenticado tem acesso no Creator (via RLS).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "N\xE3o autenticado." }],
        isError: true
      };
    }
    const supabase = supabaseForUser2(ctx);
    const { data, error } = await supabase.from("brands").select("id, name, description, tone_of_voice, created_at").order("name").limit(100);
    if (error) {
      return {
        content: [{ type: "text", text: error.message }],
        isError: true
      };
    }
    const items = data ?? [];
    const summary = items.length === 0 ? "Nenhuma marca encontrada." : items.map((b) => `\u2022 ${b.name}${b.description ? ` \u2014 ${b.description}` : ""}`).join("\n");
    return {
      content: [{ type: "text", text: summary }],
      structuredContent: { brands: items }
    };
  }
});

// src/lib/mcp/tools/list-recent-content.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_recent_content_default = defineTool3({
  name: "list_recent_content",
  title: "Listar conte\xFAdos recentes",
  description: "Lista os conte\xFAdos gerados mais recentes do usu\xE1rio autenticado no Creator (imagens, v\xEDdeos, textos). RLS j\xE1 limita a resultados que o usu\xE1rio pode ver.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(10).describe("N\xFAmero m\xE1ximo de itens a retornar (1\u201350). Padr\xE3o: 10.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "N\xE3o autenticado." }],
        isError: true
      };
    }
    const supabase = supabaseForUser3(ctx);
    const { data, error } = await supabase.from("actions").select("id, type, status, created_at, brands(name)").is("deleted_at", null).order("created_at", { ascending: false }).limit(limit);
    if (error) {
      return {
        content: [{ type: "text", text: error.message }],
        isError: true
      };
    }
    const items = data ?? [];
    const summary = items.length === 0 ? "Nenhum conte\xFAdo recente encontrado." : items.map((a) => {
      const brandName = Array.isArray(a.brands) ? a.brands[0]?.name : a.brands?.name;
      return `\u2022 [${a.type}] ${brandName ?? "\u2014"} \xB7 ${a.status} \xB7 ${a.created_at}`;
    }).join("\n");
    return {
      content: [{ type: "text", text: summary }],
      structuredContent: { items }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "lcpmqnkorcsclmpfbizr";
var mcp_default = defineMcp({
  name: "creator-mcp",
  title: "Creator (Lefil) MCP",
  version: "0.1.0",
  instructions: "Ferramentas do Creator (Lefil). Use `get_credits` para consultar cr\xE9ditos, `list_brands` para listar marcas do usu\xE1rio e `list_recent_content` para ver conte\xFAdos gerados recentes. Todas as ferramentas atuam como o usu\xE1rio autenticado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_credits_default, list_brands_default, list_recent_content_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
